### ISSUE TITLE
How to set HBA mode on RAID controller

### ISSUE THREAD

**Issue by kmerachev** [dell/dellemc-openmanage-ansible-modules#326]
##### Question
How can be set HBA mode on RAID controller?

##### Details
I'm writing automation using ansible and need to be able to set HBA mode on RAID controller (PERC H730P Mini), but I don't see any parameter for this neither in dellemc_idrac_storage_volume or idrac_redfish_storage_controller.
The only thing I found is that the mode is present in the output of idrac_server_config_profile, but not sure if I can set it through importing a server config profile.

**Comment by dafoyiming** [comment]
@anupamaloke 
My aid is to change the mode of PERC h740p mini from Raid to eHBA via this ansible collection. 

- name: Set controller attributes.
dellemc.openmanage.idrac_redfish_storage_controller:
  baseuri:"[f inventory hostname }]"
  username:"¡f idrac user +"
  password: "{{ idrac password }]"
  controller id: RAID. Integrated.1-1 attributes:
      ControllerMode: HBA
  apply time: Immediate

BUT, 
'msg": "command is AssignSpare but all of the following are missing: target"
'invocation": {
   "module_args": {
       "baseuri": "*******"
       "username": "root!
       "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
       "controller id": "RAID. Integrated.1-1"
       "attributes": {
            "ControllerMode": "HBA"
       }, "apply_time": "OnReset"
   "command": "AssianSpare"
   "mode": "LKM",
   "volume_id": null,
   "target": null,
  "key": null,
  "key_id": null,
   "old key": null

I refer to the official guide, but not work. would you please help with this? And any workaround is acceptable. 

BTW, there may be some typos in my example, please ignore them. that's caused by copy/paste. 
MY idrac version is 5.10.30 . bios version .2.14.2

**Comment by rajshekarp87** [comment]
@kmerachev @dafoyiming 
Please use below playbook to configure ControllerMode.

  - name: Configure ControllerMode
    dellemc.openmanage.idrac_redfish_storage_controller:
     baseuri: "{{ baseuri }}"
     username: "{{ username }}"
     password: "{{ password }}"
     ca_path: "{{ ca_path }}"
     controller_id: RAID.Slot.1-1
     attributes:
      ControllerMode: HBA
     job_wait: true

@dafoyiming 
If you are using older version of collection, kindly update to latest (8.0.0)

**Comment by dafoyiming** [comment]
@anupamaloke thank U

previously,I used old version with the plugin module. I did updated the module, and the error changed

{
  "msg": "'NoneType' object has no attribute 'get'",
  "exception": "  File \"/tmp/ansible_dellemc.openmanage.idrac_redfish_storage_controller_payload_pxrjdqfd/ansible_dellemc.openmanage.idrac_redfish_storage_controller_payload.zip/ansible_collections/dellemc/openmanage/plugins/modules/idrac_redfish_storage_controller.py\", line 1051, in main\n  File \"/tmp/ansible_dellemc.openmanage.idrac_redfish_storage_controller_payload_pxrjdqfd/ansible_dellemc.openmanage.idrac_redfish_storage_controller_payload.zip/ansible_collections/dellemc/openmanage/plugins/modules/idrac_redfish_storage_controller.py\", line 966, in set_attributes\n",
  "invocation": {
    "module_args": {
      "baseuri": "idrac-7QDTYP3.oob.hkintegrationlab.com",
      "username": "root",
      "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
      "controller_id": "RAID.Integrated.1-1",
      "attributes": {
        "CurrentControllerMode": "HBA"
      },
      "job_wait": true,
      "mode": "LKM",
      "apply_time": "Immediate",
      "job_wait_timeout": 120,
      "validate_certs": true,
      "timeout": 30,
      "command": null,
      "volume_id": null,
      "target": null,
      "key": null,
      "key_id": null,
      "old_key": null,
      "maintenance_window": null,
      "size": null,
      "ca_path": null
    }
  },

My idrac version is 5.10.30.00

**Comment by dafoyiming** [comment]
Correct a typo in above from

CurrentControllerMode to ControllerMode

**Comment by dafoyiming** [comment]
@anupamaloke 

I got the error fixed after upgrading idrac firmware to 6+

**Comment by anupamaloke** [comment]
@dafoyiming, thanks for sharing the update and glad that it worked.

**Comment by anupamaloke** [comment]
Closing this as storage controller OEM attributes configuration support for iDRAC 9 has been added in #468. For iDRAC7 and 8, one will have to continue using the SCP for storage controller OEM attributes configuration.
